service: resize-images 

provider:
  name: aws
  runtime: python3.6
  versonFunctions: false
  memorySize: 128
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: echo/hello
          method: get

