service: resize-images 

provider:
  name: aws
  runtime: python3.6
  versonFunctions: false
  memorySize: 256
  region: us-west-1
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      "s3:*"
    Resource:
      Fn::Join:
      - ""
      - - "arn:aws:s3:::*"

functions:
  hello:
    handler: handler.handle_hello
    events:
      - http:
          path: echo/hello
          method: get
  image_resize:
    handler: handler.handle_resize_image
    events:
      - existingS3:
          bucket: exc-photos
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg

plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3
